begin;

-- Preserve the two existing personal profiles while normalizing their IDs.
do $$
begin
  if exists (select 1 from public.admin_partners where id = 'P001')
     and exists (select 1 from public.admin_partners where id = 'p_douyin_001') then
    raise exception 'Cannot rename P001: p_douyin_001 already exists.';
  end if;
  if exists (select 1 from public.admin_partners where id = 'P002')
     and exists (select 1 from public.admin_partners where id = 'p_douyin_002') then
    raise exception 'Cannot rename P002: p_douyin_002 already exists.';
  end if;
end $$;

with id_map(old_id, new_id) as (
  values ('P001', 'p_douyin_001'), ('P002', 'p_douyin_002')
)
insert into public.admin_partners (id, visibility, payload, created_at, updated_at)
select
  id_map.new_id,
  source.visibility,
  jsonb_set(source.payload, '{id}', to_jsonb(id_map.new_id), true),
  source.created_at,
  now()
from id_map
join public.admin_partners source on source.id = id_map.old_id
on conflict (id) do nothing;

with id_map(old_id, new_id) as (
  values ('P001', 'p_douyin_001'), ('P002', 'p_douyin_002')
)
insert into public.partner_visibility (id, visibility, updated_at)
select id_map.new_id, coalesce(source.visibility, partner.visibility, 'public'), now()
from id_map
left join public.partner_visibility source on source.id = id_map.old_id
left join public.admin_partners partner on partner.id = id_map.new_id
where partner.id is not null
on conflict (id) do update set
  visibility = excluded.visibility,
  updated_at = excluded.updated_at;

update public.admin_partners
set payload = replace(
  replace(payload::text, '"P001"', '"p_douyin_001"'),
  '"P002"', '"p_douyin_002"'
)::jsonb,
updated_at = now()
where payload::text like '%"P001"%' or payload::text like '%"P002"%';

update public.cooperation_feedback
set payload = replace(
  replace(payload::text, '"P001"', '"p_douyin_001"'),
  '"P002"', '"p_douyin_002"'
)::jsonb,
updated_at = now()
where payload::text like '%"P001"%' or payload::text like '%"P002"%';

update public.due_diligence_requests
set payload = replace(
  replace(payload::text, '"P001"', '"p_douyin_001"'),
  '"P002"', '"p_douyin_002"'
)::jsonb,
updated_at = now()
where payload::text like '%"P001"%' or payload::text like '%"P002"%';

delete from public.partner_visibility where id in ('P001', 'P002');
delete from public.admin_partners where id in ('P001', 'P002');

insert into public.admin_partners (id, visibility, payload, updated_at)
values
('p_douyin_003','public','{"id":"p_douyin_003","name":"护肤学霸蚊子（测评版）","displayName":"护肤学霸蚊子（测评版）","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["美妆护肤","成分护肤","产品测评"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"复旦/东华双学位，皮肤管理师，长期研究护肤品成分。公开资料待核验。","followerCount":"98.6万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAAbeIim9TwvE2xb5ibjW9VwCUh6AJjgke2oQuuFyvsrle-d3mlX4B3pFsLV2mxfLdA"}'::jsonb,now()),
('p_douyin_004','public','{"id":"p_douyin_004","name":"护肤硕士季学长","displayName":"护肤硕士季学长","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["美妆护肤","成分护肤","真实体验"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"材料与化工硕士，侧重护肤成分与真实体验。公开资料待核验。","followerCount":"32.9万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAAorPZhX6iEQTvRLoC-xOtWnB6esJzWzvxnUtt9qZwK_w"}'::jsonb,now()),
('p_douyin_005','public','{"id":"p_douyin_005","name":"美妆护肤测评","displayName":"美妆护肤测评","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["美妆护肤","彩妆","产品测评"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"主打彩妆护肤真实体验与客观评价。公开资料待核验。","followerCount":"9.3万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAAozruqaRexe4A9EPZ6gVY1pU2Vfe-q-8crV7zlT5La6E"}'::jsonb,now()),
('p_douyin_006','public','{"id":"p_douyin_006","name":"米多多护肤","displayName":"米多多护肤","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["美妆护肤","成分护肤","个护测评"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"皮肤管理师、营养师背景，侧重成分和个护测评。公开资料待核验。","followerCount":"93.2万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAANpcJeu5pT1ExUCBr0wWzCTJnf8-fe9YBxU-xL2o2U00"}'::jsonb,now()),
('p_douyin_007','public','{"id":"p_douyin_007","name":"kk和王博士（测评版）","displayName":"kk和王博士（测评版）","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["美妆护肤","硬核测评","生活好物"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"成分护肤与多品类实验型测评，有实验室内容标签。公开资料待核验。","followerCount":"52.9万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAAGOjyrcsnEWDoMrIK2nzxG7_kPxwoc39tauRH0uktbyg"}'::jsonb,now()),
('p_douyin_008','public','{"id":"p_douyin_008","name":"老爸评测美妆护肤","displayName":"老爸评测美妆护肤","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["品牌账号","主播达人"],"platforms":["抖音"],"categories":["美妆护肤","直播带货"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"直播与短视频合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"老爸评测公开子账号，主营美妆护肤及百货直播。公开资料待核验。","followerCount":"16.9万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAA_GePRIDcz1sCvmzI1olt47OKduiau2v4sRU5XSXctI9nUOpoLWcyIqqgrs4ba7lT"}'::jsonb,now()),
('p_douyin_009','public','{"id":"p_douyin_009","name":"成分测评漆仔","displayName":"成分测评漆仔","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["美妆护肤","成分研发","产品测评"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"成分研发与品牌内测背景，覆盖多品类产品测评。公开资料待核验。","followerCount":"97.7万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAA2SEXIDZASWsnehzvn_fyfPH5k4F12WOsiQvEhWuBPAA"}'::jsonb,now()),
('p_douyin_010','public','{"id":"p_douyin_010","name":"朵儿朵护肤","displayName":"朵儿朵护肤","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["美妆护肤","皮肤护理","护肤知识"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"护肤行业与皮肤管理背景，偏知识分享。公开资料待核验。","followerCount":"68.1万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAAc9ArB65Zfa7Lx8jg6qPSLRopTDWcOv8CqCQwGZQEmlDz6Twj8kpqhVItta4XXROd"}'::jsonb,now()),
('p_douyin_011','public','{"id":"p_douyin_011","name":"护肤测评","displayName":"护肤测评","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["美妆护肤","科学护肤","国货好物"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"分享科学护肤、皮肤护理知识和国货好物。公开资料待核验。","followerCount":"1040","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAAShnoSfmdzRz8sgjfzvekjlVc1kKzv0251VzAk2ovR_fYwTonuwMIJDVKUGSUCz7k"}'::jsonb,now()),
('p_douyin_012','public','{"id":"p_douyin_012","name":"成分测评源哥","displayName":"成分测评源哥","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["美妆护肤","母婴","生活测评"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"长期成分研究，覆盖护肤、母婴及生活好物测评。公开资料待核验。","followerCount":"70.0万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAA47mwtQletbQYoMWUr0FZJrdzjx5925jCj5vo5S87Kzwz6xST3Wy90ZIMigzRGFZy"}'::jsonb,now()),
('p_douyin_013','public','{"id":"p_douyin_013","name":"子轩成分测评","displayName":"子轩成分测评","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["美妆护肤","成分护肤","痘敏肌"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"皮肤管理师背景，侧重成分、痘敏肌和护肤行动。公开资料待核验。","followerCount":"125.8万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAAgZSpQbMp20nqbt4UwK6YwTyhZZQgVX7_YVj3w4jKIiDFpUwyiPtamMgo1ObrJFoo"}'::jsonb,now()),
('p_douyin_014','public','{"id":"p_douyin_014","name":"洋叔de测评","displayName":"洋叔de测评","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人","团队"],"platforms":["抖音"],"categories":["美妆护肤","全品类测评","科学生活"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"美妆创作者，实验室型全品类测评。公开资料待核验。","followerCount":"136.4万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAAJEgSQEw4_1cwPWmXx4E5-WNMOGQr-WvIbfkvhipt-9RltV3yNJWk79suj03QDRwg"}'::jsonb,now()),
('p_douyin_015','public','{"id":"p_douyin_015","name":"瑞思白白（测评版）","displayName":"瑞思白白（测评版）","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["美妆护肤","产品测评","种草内容"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"干敏瑕疵皮标签，偏戏剧化测评与种草内容。公开资料待核验。","followerCount":"155.8万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAAJjo4upWIheBNG1ttOTi3x_7B82jCm9Ltsb2tWkyjrlQelHsIlldLAWP0RqDColhX"}'::jsonb,now()),
('p_douyin_016','public','{"id":"p_douyin_016","name":"小法的护肤笔记","displayName":"小法的护肤笔记","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["美妆护肤","生活","变美"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"干敏皮标签，覆盖护肤、美妆及生活内容。公开资料待核验。","followerCount":"116.9万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAA6uZqAdrksLGLPU7L0HDNARY8tKIQ38rvHVzkX6DuUQgff-bjOvNegTTZrinbrbjN"}'::jsonb,now()),
('p_douyin_017','public','{"id":"p_douyin_017","name":"大杰护肤品研发师","displayName":"大杰护肤品研发师","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人","品牌创始人"],"platforms":["抖音"],"categories":["美妆护肤","科学护肤","产品研发"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"护肤品研发从业背景，分享科学护肤及产品。公开资料待核验。","followerCount":"157.6万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAAfp--LZiCO6oU8clFcVUbHo92Ih27oXGiXnbtOxLti-rRoSPfF7zYYMGYAOtqCP5Q"}'::jsonb,now()),
('p_douyin_018','public','{"id":"p_douyin_018","name":"小Ray零食控","displayName":"小Ray零食控","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["食品饮料","零食测评","探店"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"甜食、零食新品测评及逛吃探店。公开资料待核验。","followerCount":"86.7万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAA5v8HrZHqP-62wfkftOYSI6vMhSOUz_dZoqsrjzVC_G4"}'::jsonb,now()),
('p_douyin_019','public','{"id":"p_douyin_019","name":"阿灿零食测评","displayName":"阿灿零食测评","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["食品饮料","零食测评","自费测评"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"强调自费购买、无滤镜和真实评价。公开资料待核验。","followerCount":"6.1万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAApLJV6L49BcTUE9NMFe6bgf-gwSX39P6TDI1QGBmlw48n09BgqNBDVznYcRd2znql"}'::jsonb,now()),
('p_douyin_020','public','{"id":"p_douyin_020","name":"阿荣零食测评","displayName":"阿荣零食测评","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["食品饮料","零食测评","美食分享"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"分享零食及日常好吃好玩的内容。公开资料待核验。","followerCount":"18.9万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAAtwSrMY6PuQb7rR83eyij48FK8WSN3wObjUR_RuAk2r8C-mnYNAIMnj1IORm2dwRY"}'::jsonb,now()),
('p_douyin_021','public','{"id":"p_douyin_021","name":"荣哥零食测评","displayName":"荣哥零食测评","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["食品饮料","零食测评","真实评价"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"专注各类零食测评，强调真实。公开资料待核验。","followerCount":"14.6万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAAUAwqnR0FjFW416H80lMtQqsHY_MKuL5ynZTJ8R6YDikpZlqb3UoWt_UaymeuhiM8"}'::jsonb,now()),
('p_douyin_022','public','{"id":"p_douyin_022","name":"芝士小奶盖（测评版）","displayName":"芝士小奶盖（测评版）","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["食品饮料","零食测评"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"以体验各类零食为主要内容。公开资料待核验。","followerCount":"48.6万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAAlSc6n9u0huEHYV9gpotLE4dG9P420AHnpTLJLJx3-nVuezCy67tZ7fl_x93SSUJ0"}'::jsonb,now()),
('p_douyin_023','public','{"id":"p_douyin_023","name":"甜甜的轻食零食","displayName":"甜甜的轻食零食","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["食品饮料","轻食零食","好物分享"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"轻食零食与精选好物分享，橱窗属性明显。公开资料待核验。","followerCount":"76.9万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAAK20qQQHJi2Ct2lToVzB6CPjz8ZK5XSbdCtft2kN7POg"}'::jsonb,now()),
('p_douyin_024','public','{"id":"p_douyin_024","name":"小绵羊零食测评","displayName":"小绵羊零食测评","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["食品饮料","美食测评","粉丝选题"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"非专业个人口味测评，接受粉丝选题。公开资料待核验。","followerCount":"15.9万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAA-VlAZlpx43T2rO_iX2pSKcP-Tz0bH0LkMIFims4gMvthHK5VwwAqBshgEaAu5AxW"}'::jsonb,now()),
('p_douyin_025','public','{"id":"p_douyin_025","name":"胖兔零食测评","displayName":"胖兔零食测评","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["食品饮料","零食测评"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"个人零食与试吃内容。公开资料待核验。","followerCount":"10.8万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAAJ4HdADtfaThwx8oxqC_qRcPMoAT9Dil84hK-rFDJQxy2yhTr-4l48DDVQLMLn3Nu"}'::jsonb,now()),
('p_douyin_026','public','{"id":"p_douyin_026","name":"零食测评","displayName":"零食测评","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["食品饮料","美食分享","成长型账号"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"成长型美食账号，分享零食与日常。公开资料待核验。","followerCount":"1365","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAAH3SUyw8a4RwVQZ2dLgR6ZgsSjLpVw4yvRkJrdzirYVvcgqCxh5Z1qKUUT3_6uSpx"}'::jsonb,now()),
('p_douyin_027','public','{"id":"p_douyin_027","name":"小锦鲤零食测评","displayName":"小锦鲤零食测评","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["食品饮料","美食测评","粉丝选题"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"非专业个人口味测评，接受粉丝选题。公开资料待核验。","followerCount":"11.1万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAAd8fOGUo_6TMoJsRypt6yaXIJ5_rIsJdgRfJjEqDCOkA_qrrbz0fAiFxLD-B_sCaF"}'::jsonb,now()),
('p_douyin_028','public','{"id":"p_douyin_028","name":"可乐很真实！（零食测评）","displayName":"可乐很真实！（零食测评）","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["食品饮料","自费测评","真实拍摄"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"强调无广告、自费购买、无滤镜真实拍摄。公开资料待核验。","followerCount":"7.6万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAAHfm-Q3hjPaIvwh0n8S0P16dJC-PUWgOdLcmemFEGBwcsnc7HJzMD_G4TTocdfKAc"}'::jsonb,now()),
('p_douyin_029','public','{"id":"p_douyin_029","name":"洺洺的轻食零食","displayName":"洺洺的轻食零食","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["食品饮料","低卡轻食","零食种草"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"低卡轻食与热门零食分享，橱窗属性明显。公开资料待核验。","followerCount":"54.1万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAAoHgFyA1rQY8nYvwQTSNFJ6e_6KRXNwxB0vzNEMTWaCI"}'::jsonb,now()),
('p_douyin_030','public','{"id":"p_douyin_030","name":"汐汐 零食小铺","displayName":"汐汐 零食小铺","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人","带货账号"],"platforms":["抖音"],"categories":["食品饮料","零食好物","橱窗"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频及橱窗合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"好物测评与橱窗分销导向。公开资料待核验。","followerCount":"18.6万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAAPJbEZTow8PStw_9vs9JErFEU3DBiIumEitoBjylWvK4"}'::jsonb,now()),
('p_douyin_031','public','{"id":"p_douyin_031","name":"小橙子轻食零食","displayName":"小橙子轻食零食","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["食品饮料","轻食餐","生活记录"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"轻食餐与生活记录内容。公开资料待核验。","followerCount":"60.6万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAAonJ3fYCMoumMhGC-uA7oaHedGgl6NeqJK3ZUMp4Q8OU"}'::jsonb,now()),
('p_douyin_032','public','{"id":"p_douyin_032","name":"麻薯测评局","displayName":"麻薯测评局","entityType":"person","roleTitle":"抖音达人","city":"","coverageArea":[],"partnerType":["主播达人"],"platforms":["抖音"],"categories":["食品饮料","数码","零食测评"],"priceRange":"待补充","cooperationModels":["待确认"],"customerProfile":"待补充","salesScenario":"短视频内容合作","verificationStatus":"未核验","riskLevel":"low","riskTags":[],"scores":{"authenticity":0,"fulfillment":0,"categoryFit":0,"conversionFeedback":0,"riskControl":0,"dataCompleteness":0,"overall":0},"dataSource":"抖音公开主页及搜索页","description":"数码与零食混合测评，垂直度需要复核。公开资料待核验。","followerCount":"58.7万","updatedAt":"2026-06-24","adminVisibility":"public","publicProfileUrl":"https://www.douyin.com/user/MS4wLjABAAAAltv0MExiU80-5ZUc7FQzWlARrQZzeW_MW4xRkHOB-QqO3FOtGJhO4j416kXl75s-"}'::jsonb,now())
on conflict (id) do update set
  visibility = excluded.visibility,
  payload = excluded.payload,
  updated_at = excluded.updated_at;

insert into public.partner_visibility (id, visibility, updated_at)
select id, 'public', now()
from public.admin_partners
where id between 'p_douyin_003' and 'p_douyin_032'
on conflict (id) do update set
  visibility = excluded.visibility,
  updated_at = excluded.updated_at;

commit;
